- hosts: localhost
  tasks:
    - name: "Create EC2 keys"
      ec2_key:
        name: TeamCity-1-key
        region: "{{ aws_region }}"
      register: ec2_key
    - name: "Save EC2 key"
      copy:
        content: "{{ ec2_key.key.private_key }}"
        dest: "./aws-private.pem"
        mode: 0600
      when: ec2_key.changed
